name: Lint with Pylint

on:
  pull_request:
    branches: [ main ]  # or your default branch

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13  # or your required Python version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install pylint

    - name: Run pylint
      run: |
        source venv/bin/activate
        pylint custom_components/aux_cloud --fail-under=9.0
